# Sale Prediction from Existing Customer - Logistic Regression

## 1. Importing libraries

In [1]:
import pandas as pd
import numpy as np

## 2. importing dataset from dir

In [2]:
dataset = pd.read_csv('DigitalAd_dataset.csv')

In [3]:
dataset

     Age  Salary  Status
0     18   82000       0
1     29   80000       0
2     47   25000       1
3     45   26000       1
4     46   28000       1
..   ...     ...     ...
395   35   65000       0
396   26   80000       0
397   26   52000       0
398   20   86000       0
399   32   18000       0

[400 rows x 3 columns]

## 3. Summarize dataset

In [4]:
dataset.head(5)

   Age  Salary  Status
0   18   82000       0
1   29   80000       0
2   47   25000       1
3   45   26000       1
4   46   28000       1

In [5]:
dataset.tail(5)

     Age  Salary  Status
395   35   65000       0
396   26   80000       0
397   26   52000       0
398   20   86000       0
399   32   18000       0

In [6]:
dataset.shape

(400, 3)

In [7]:
dataset.isnull().sum()

Age       0
Salary    0
Status    0
dtype: int64

In [9]:
dataset.dtypes

Age       int64
Salary    int64
Status    int64
dtype: object

##  4.Segerate dataset into X(input) & Y(output)

In [39]:
# before comma rows and after comma columns

# X = dataset.iloc[rowstart:rowend,colstart:colend]
# above form the below data is give. iloc -> means index location
X = dataset.iloc[:, :-1].values
X

array([[    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],
       [    27,  17000],
       [    33,  51000],
       [    35, 108000],
       [    30,  15000],
       [    28,  84000],
       [    23,  20000],
       [    25,  79000],
       [    27,  54000],
       [    30, 135000],
       [    31,  89000],
       [    24,  32000],
       [    18,  44000],
       [    29,  83000],
       [    35,  23000],
       [    27,  58000],
       [    24,  55000],
       [    23,  48000],
       [    28,  79000],
       [    22,  18000],
       [    32, 117000],
       [    27,  20000],
       [    25,  87000],
       [    23,  66000],
       [    32, 120000],
       [    59,  83000],
       [    24,  58000],
       [    24,  19000],
       [    23,  82000],
       [    22,  63000],
       [    31,  68000],
       [    25,  80000],
       [    24,  27000],
       [    20,  23000],
       [    33, 113000],
       [    32,  18000],
       [    34, 112000],
       [    18,  52000],
       [    22,  27000],
       [    28,  87000],
       [    26,  17000],
       [    30,  80000],
       [    39,  42000],
       [    20,  49000],
       [    35,  88000],
       [    30,  62000],
       [    31, 118000],
       [    24,  55000],
       [    28,  85000],
       [    26,  81000],
       [    35,  50000],
       [    22,  81000],
       [    30, 116000],
       [    26,  15000],
       [    29,  28000],
       [    29,  83000],
       [    35,  44000],
       [    35,  25000],
       [    28, 123000],
       [    35,  73000],
       [    28,  37000],
       [    27,  88000],
       [    28,  59000],
       [    32,  86000],
       [    33, 149000],
       [    19,  21000],
       [    21,  72000],
       [    26,  35000],
       [    27,  89000],
       [    26,  86000],
       [    38,  80000],
       [    39,  71000],
       [    37,  71000],
       [    38,  61000],
       [    37,  55000],
       [    42,  80000],
       [    40,  57000],
       [    35,  75000],
       [    36,  52000],
       [    40,  59000],
       [    41,  59000],
       [    36,  75000],
       [    37,  72000],
       [    40,  75000],
       [    35,  53000],
       [    41,  51000],
       [    39,  61000],
       [    42,  65000],
       [    26,  32000],
       [    30,  17000],
       [    26,  84000],
       [    31,  58000],
       [    33,  31000],
       [    30,  87000],
       [    21,  68000],
       [    28,  55000],
       [    23,  63000],
       [    20,  82000],
       [    30, 107000],
       [    28,  59000],
       [    19,  25000],
       [    19,  85000],
       [    18,  68000],
       [    35,  59000],
       [    30,  89000],
       [    34,  25000],
       [    24,  89000],
       [    27,  96000],
       [    41,  30000],
       [    29,  61000],
       [    20,  74000],
       [    26,  15000],
       [    41,  45000],
       [    31,  76000],
       [    36,  50000],
       [    40,  47000],
       [    31,  15000],
       [    46,  59000],
       [    29,  75000],
       [    26,  30000],
       [    32, 135000],
       [    32, 100000],
       [    25,  90000],
       [    37,  33000],
       [    35,  38000],
       [    33,  69000],
       [    18,  86000],
       [    22,  55000],
       [    35,  71000],
       [    29, 148000],
       [    29,  47000],
       [    21,  88000],
       [    34, 115000],
       [    26, 118000],
       [    34,  43000],
       [    34,  72000],
       [    23,  28000],
       [    35,  47000],
       [    25,  22000],
       [    24,  23000],
       [    31,  34000],
       [    26,  16000],
       [    31,  71000],
       [    32, 117000],
       [    33,  43000],
       [    33,  60000],
       [    31,  66000],
       [    20,  82000],
       [    33,  41000],
       [    35,  72000],
       [    28,  32000],
       [    24,  84000],
       [    19,  26000],
       [    29,  43000],
       [    19,  70000],
       [    28,  89000],
       [    34,  43000],
       [    30,  79000],
       [    20,  36000],
       [    26,  80000],
       [    35,  22000],
       [    35,  39000],
       [    49,  74000],
       [    39, 134000],
       [    41,  71000],
       [    58, 101000],
       [    47,  47000],
       [    55, 130000],
       [    52, 114000],
       [    40, 142000],
       [    46,  22000],
       [    48,  96000],
       [    52, 150000],
       [    59,  42000],
       [    35,  58000],
       [    47,  43000],
       [    60, 108000],
       [    49,  65000],
       [    40,  78000],
       [    46,  96000],
       [    59, 143000],
       [    41,  80000],
       [    35,  91000],
       [    37, 144000],
       [    60, 102000],
       [    35,  60000],
       [    37,  53000],
       [    36, 126000],
       [    56, 133000],
       [    40,  72000],
       [    42,  80000],
       [    35, 147000],
       [    39,  42000],
       [    40, 107000],
       [    49,  86000],
       [    38, 112000],
       [    46,  79000],
       [    40,  57000],
       [    37,  80000],
       [    46,  82000],
       [    53, 143000],
       [    42, 149000],
       [    38,  59000],
       [    50,  88000],
       [    56, 104000],
       [    41,  72000],
       [    51, 146000],
       [    35,  50000],
       [    57, 122000],
       [    41,  52000],
       [    35,  97000],
       [    44,  39000],
       [    37,  52000],
       [    48, 134000],
       [    37, 146000],
       [    50,  44000],
       [    52,  90000],
       [    41,  72000],
       [    40,  57000],
       [    58,  95000],
       [    45, 131000],
       [    35,  77000],
       [    36, 144000],
       [    55, 125000],
       [    35,  72000],
       [    48,  90000],
       [    42, 108000],
       [    40,  75000],
       [    37,  74000],
       [    47, 144000],
       [    40,  61000],
       [    43, 133000],
       [    59,  76000],
       [    60,  42000],
       [    39, 106000],
       [    57,  26000],
       [    57,  74000],
       [    38,  71000],
       [    49,  88000],
       [    52,  38000],
       [    50,  36000],
       [    59,  88000],
       [    35,  61000],
       [    37,  70000],
       [    52,  21000],
       [    48, 141000],
       [    37,  93000],
       [    37,  62000],
       [    48, 138000],
       [    41,  79000],
       [    37,  78000],
       [    39, 134000],
       [    49,  89000],
       [    55,  39000],
       [    37,  77000],
       [    35,  57000],
       [    36,  63000],
       [    42,  73000],
       [    43, 112000],
       [    45,  79000],
       [    46, 117000],
       [    58,  38000],
       [    48,  74000],
       [    37, 137000],
       [    37,  79000],
       [    40,  60000],
       [    42,  54000],
       [    51, 134000],
       [    47, 113000],
       [    36, 125000],
       [    38,  50000],
       [    42,  70000],
       [    39,  96000],
       [    38,  50000],
       [    49, 141000],
       [    39,  79000],
       [    39,  75000],
       [    54, 104000],
       [    35,  55000],
       [    45,  32000],
       [    36,  60000],
       [    52, 138000],
       [    53,  82000],
       [    41,  52000],
       [    48,  30000],
       [    48, 131000],
       [    41,  60000],
       [    41,  72000],
       [    42,  75000],
       [    36, 118000],
       [    47, 107000],
       [    38,  51000],
       [    48, 119000],
       [    42,  65000],
       [    40,  65000],
       [    57,  60000],
       [    36,  54000],
       [    58, 144000],
       [    35,  79000],
       [    38,  55000],
       [    39, 122000],
       [    53, 104000],
       [    35,  75000],
       [    38,  65000],
       [    47,  51000],
       [    47, 105000],
       [    41,  63000],
       [    53,  72000],
       [    54, 108000],
       [    39,  77000],
       [    38,  61000],
       [    38, 113000],
       [    37,  75000],
       [    42,  90000],
       [    37,  57000],
       [    36,  99000],
       [    60,  34000],
       [    54,  70000],
       [    41,  72000],
       [    40,  71000],
       [    42,  54000],
       [    43, 129000],
       [    53,  34000],
       [    47,  50000],
       [    42,  79000],
       [    42, 104000],
       [    59,  29000],
       [    58,  47000],
       [    46,  88000],
       [    38,  71000],
       [    54,  26000],
       [    60,  46000],
       [    60,  83000],
       [    39,  73000],
       [    59, 130000],
       [    37,  80000],
       [    46,  32000],
       [    46,  74000],
       [    42,  53000],
       [    41,  87000],
       [    58,  23000],
       [    42,  64000],
       [    48,  33000],
       [    44, 139000],
       [    49,  28000],
       [    57,  33000],
       [    56,  60000],
       [    49,  39000],
       [    39,  71000],
       [    47,  34000],
       [    48,  35000],
       [    48,  33000],
       [    47,  23000],
       [    45,  45000],
       [    60,  42000],
       [    39,  59000],
       [    46,  41000],
       [    51,  23000],
       [    50,  20000],
       [    36,  33000],
       [    49,  36000],
       [    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000]])

In [40]:
Y = dataset.iloc[:, -1].values
Y

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0])

## 5. Splitting Dataset into Train and Test

In [41]:
from sklearn.model_selection import train_test_split
# 0.25 na testing 25% and training 80% ,, random_state => meaning random 75% data from the dataset
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size = 0.25,random_state = 0)

### Feature Scaling 
- we scale our data to make all the features contribute equally to the result
- Fit_transform - fit method is calculating the mean and variance of each of the features persent in our data
- Transform - Transform method is transforming all the features using the respective mean and variance
- we want our test data to be a completely new and surprise set of our model

In [42]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) # always give fit for training
X_test = sc.transform(X_test)

In [43]:
X_train

array([[ 0.97446763,  0.56400811],
       [-1.52088611, -1.28151705],
       [ 0.30264162,  0.03671521],
       [-0.36918439, -0.81281224],
       [ 0.49459191,  1.20847722],
       [-0.1772341 ,  0.82765456],
       [-0.27320924, -0.78351819],
       [ 0.39861676,  0.24177356],
       [-0.27320924,  0.00742116],
       [ 0.01471619, -0.60775389],
       [ 0.11069133,  0.00742116],
       [-0.46515953,  2.29235707],
       [ 0.39861676, -0.02187289],
       [-0.27320924, -1.28151705],
       [ 1.93421906, -1.39869325],
       [-0.27320924,  2.23376897],
       [ 0.11069133,  1.03271291],
       [-0.56113467,  1.44282962],
       [ 0.97446763,  1.85294632],
       [ 0.30264162,  0.03671521],
       [-1.13698554, -1.04716465],
       [-0.08125895,  0.27106761],
       [ 0.30264162, -0.54916579],
       [-0.27320924, -0.60775389],
       [ 0.87849248, -1.39869325],
       [ 0.78251734, -0.34410744],
       [-0.46515953, -1.252223  ],
       [ 0.20666648,  0.12459736],
       [ 0.39861676,  0.97412481],
       [-0.56113467,  1.35494747],
       [-0.46515953, -0.05116694],
       [-0.56113467,  2.32165112],
       [-0.75308496,  0.27106761],
       [ 1.16641791, -0.78351819],
       [ 0.20666648,  1.06200696],
       [ 0.20666648, -0.40269554],
       [ 0.30264162, -0.31481339],
       [ 0.20666648,  2.08729872],
       [ 1.45434334,  0.97412481],
       [-1.04101039,  1.94082847],
       [-1.32893582, -1.39869325],
       [-0.27320924, -0.92998845],
       [-0.94503525,  0.38824381],
       [-0.75308496, -1.57445755],
       [ 1.07044277,  0.50542001],
       [-0.1772341 , -0.54916579],
       [ 0.11069133,  0.06600926],
       [ 0.68654219,  1.76506417],
       [-0.27320924,  0.76906646],
       [-0.65710982, -0.37340149],
       [ 0.87849248,  1.00341886],
       [-0.94503525, -0.46128364],
       [-0.08125895,  0.24177356],
       [ 0.39861676, -0.16834314],
       [ 0.39861676,  0.27106761],
       [-1.13698554, -1.63304565],
       [-0.08125895,  0.21247951],
       [-1.80881154,  0.41753786],
       [ 2.03019421, -0.84210629],
       [ 1.07044277,  2.05800467],
       [-0.1772341 , -0.22693124],
       [ 0.30264162, -1.1936349 ],
       [-1.04101039, -0.49057769],
       [ 0.68654219, -0.75422414],
       [-0.27320924, -0.69563604],
       [-0.75308496,  1.88224037],
       [ 1.26239306,  2.20447492],
       [-0.08125895,  0.00742116],
       [-0.94503525, -0.98857655],
       [-0.36918439,  1.20847722],
       [-0.65710982,  0.00742116],
       [ 0.39861676,  0.06600926],
       [ 0.87849248, -0.81281224],
       [-1.04101039, -0.37340149],
       [ 0.30264162,  0.03671521],
       [ 0.97446763,  0.09530331],
       [ 0.20666648,  0.12459736],
       [-1.04101039, -1.4865754 ],
       [ 1.83824392, -0.31481339],
       [-1.13698554,  0.27106761],
       [ 0.78251734,  0.32965571],
       [-0.94503525,  0.41753786],
       [ 0.30264162, -0.75422414],
       [ 0.78251734, -0.87140035],
       [ 0.01471619,  1.20847722],
       [-0.27320924, -0.31481339],
       [-0.75308496, -1.63304565],
       [-0.36918439, -0.81281224],
       [-0.08125895,  0.27106761],
       [-0.08125895,  0.65189026],
       [-1.32893582, -0.37340149],
       [ 0.01471619, -0.16834314],
       [ 1.93421906, -0.69563604],
       [-0.46515953, -0.57845984],
       [ 0.87849248, -1.34010515],
       [ 0.11069133, -0.84210629],
       [-1.61686125,  0.50542001],
       [-0.1772341 ,  1.61859392],
       [ 0.97446763, -1.10575275],
       [ 0.78251734,  0.24177356],
       [-0.65710982,  0.15389141],
       [ 0.59056705, -0.92998845],
       [ 1.07044277,  0.44683191],
       [ 0.30264162,  0.24177356],
       [ 1.64629363, -0.92998845],
       [ 1.45434334,  0.32965571],
       [-0.08125895,  2.20447492],
       [-0.65710982,  0.53471406],
       [ 0.78251734,  0.73977241],
       [-1.04101039,  0.38824381],
       [ 0.11069133, -0.84210629],
       [-1.13698554,  0.03671521],
       [ 1.45434334,  0.03671521],
       [-1.52088611, -1.5451635 ],
       [ 1.3583682 ,  0.56400811],
       [-0.75308496,  0.53471406],
       [-1.04101039,  0.53471406],
       [ 0.11069133, -0.28551934],
       [-1.13698554, -1.6037516 ],
       [-1.04101039, -0.40269554],
       [ 1.16641791, -1.4865754 ],
       [ 1.55031849, -0.02187289],
       [-1.04101039, -0.37340149],
       [-1.61686125, -1.6037516 ],
       [ 0.68654219,  0.24177356],
       [-0.8490601 , -1.252223  ],
       [-0.27320924,  0.03671521],
       [-1.23296068, -1.10575275],
       [-0.65710982,  1.38424152],
       [ 0.87849248, -1.1936349 ],
       [ 0.97446763, -1.10575275],
       [ 1.74226877,  1.82365227],
       [ 1.07044277, -1.0178706 ],
       [-1.13698554, -0.81281224],
       [ 1.16641791,  0.50542001],
       [-0.36918439,  0.03671521],
       [ 0.20666648, -0.34410744],
       [-1.42491097, -1.252223  ],
       [-0.94503525,  1.53071177],
       [ 0.30264162,  0.00742116],
       [-1.13698554, -0.54916579],
       [-0.75308496,  0.47612596],
       [ 0.87849248,  2.14588682],
       [ 0.11069133,  1.85294632],
       [-0.08125895,  2.14588682],
       [ 0.97446763, -1.04716465],
       [ 0.30264162, -0.57845984],
       [-0.27320924, -0.9592825 ],
       [-0.36918439,  1.29635937],
       [-1.52088611, -0.46128364],
       [-0.65710982,  0.09530331],
       [ 1.3583682 , -1.45728135],
       [-0.27320924, -0.60775389],
       [-0.27320924, -0.51987174],
       [-0.27320924,  0.12459736],
       [ 2.03019421,  2.11659277],
       [ 0.87849248,  1.06200696],
       [-0.1772341 , -0.60775389],
       [-0.08125895, -0.54916579],
       [ 0.20666648, -0.16834314],
       [ 1.64629363,  1.58929987],
       [ 0.30264162, -0.54916579],
       [-0.94503525, -0.78351819],
       [ 0.39861676,  2.29235707],
       [ 1.3583682 ,  1.97012252],
       [ 0.68654219, -1.3108111 ],
       [ 0.11069133,  1.85294632],
       [-1.80881154, -1.34010515],
       [-0.75308496,  1.32565342],
       [-1.13698554,  0.27106761],
       [ 0.11069133,  0.12459736],
       [ 2.12616935, -0.84210629],
       [ 0.49459191,  1.70647607],
       [-0.75308496,  0.24177356],
       [ 2.12616935, -0.72493009],
       [-0.8490601 ,  0.35894976],
       [ 2.12616935, -0.84210629],
       [ 0.87849248, -1.4865754 ],
       [ 0.01471619, -0.60775389],
       [-1.04101039,  0.50542001],
       [ 2.03019421,  0.50542001],
       [-1.32893582, -1.1350468 ],
       [ 1.26239306, -1.39869325],
       [-1.7128364 , -1.39869325],
       [-1.32893582, -0.46128364],
       [ 0.97446763,  2.05800467],
       [ 2.03019421,  0.35894976],
       [ 2.12616935,  0.91553671],
       [ 0.97446763,  1.41353557],
       [ 0.01471619, -0.57845984],
       [ 0.30264162, -0.22693124],
       [-0.75308496,  1.06200696],
       [ 0.20666648, -0.40269554],
       [-1.90478668, -0.54916579],
       [ 1.55031849,  0.97412481],
       [-0.36918439, -1.34010515],
       [ 1.07044277,  0.09530331],
       [-0.75308496, -0.63704794],
       [-0.94503525,  0.24177356],
       [-1.90478668,  0.32965571],
       [ 2.12616935,  1.09130101],
       [-0.08125895, -0.40269554],
       [ 0.01471619, -0.28551934],
       [-0.27320924, -1.4865754 ],
       [-0.8490601 , -0.81281224],
       [ 0.49459191,  1.82365227],
       [-1.13698554,  0.44683191],
       [ 1.07044277, -1.252223  ],
       [ 0.01471619,  0.27106761],
       [ 2.03019421, -1.22292895],
       [-0.46515953, -0.81281224],
       [-0.27320924,  0.50542001],
       [-0.1772341 , -0.31481339],
       [-1.42491097, -0.13904909],
       [-0.27320924,  0.59330216],
       [-0.08125895,  0.18318546],
       [ 0.01471619, -0.34410744],
       [-0.08125895, -1.10575275],
       [-0.8490601 ,  0.12459736],
       [-0.94503525,  0.53471406],
       [-1.32893582,  0.53471406],
       [ 2.12616935,  0.35894976],
       [-1.7128364 ,  0.44683191],
       [ 0.01471619,  0.00742116],
       [ 0.01471619, -0.46128364],
       [ 0.20666648,  0.21247951],
       [-0.27320924,  0.06600926],
       [-1.42491097, -0.22693124],
       [ 0.39861676, -0.49057769],
       [ 0.39861676, -0.19763719],
       [-1.61686125,  0.03671521],
       [-0.27320924, -1.34010515],
       [-0.27320924, -0.28551934],
       [-1.61686125, -0.08046099],
       [ 0.39861676, -0.49057769],
       [-1.32893582, -1.28151705],
       [-0.1772341 , -0.49057769],
       [ 2.03019421,  0.15389141],
       [ 1.55031849, -1.3108111 ],
       [-1.42491097, -0.66634199],
       [ 0.30264162, -0.34410744],
       [ 0.59056705,  1.99941657],
       [ 0.97446763,  1.97012252],
       [ 0.78251734,  0.50542001],
       [-0.8490601 ,  0.35894976],
       [-1.42491097,  0.32965571],
       [ 1.45434334, -1.0764587 ],
       [-0.27320924, -0.34410744],
       [ 0.20666648, -0.31481339],
       [-0.27320924,  1.09130101],
       [-1.7128364 , -1.0178706 ],
       [-1.23296068, -1.4279873 ],
       [-1.90478668,  0.44683191],
       [ 1.93421906,  0.71047836],
       [ 1.07044277, -0.16834314],
       [-1.42491097, -1.4865754 ],
       [-1.23296068,  0.24177356],
       [-1.90478668, -0.08046099],
       [-0.27320924, -1.4279873 ],
       [ 1.07044277, -0.92998845],
       [-0.08125895,  1.94082847],
       [ 0.78251734,  0.09530331],
       [-1.23296068,  0.56400811],
       [ 0.78251734,  1.35494747],
       [ 1.83824392, -1.10575275],
       [-1.80881154, -1.3108111 ],
       [-0.08125895, -0.46128364],
       [ 0.39861676,  0.56400811],
       [ 0.01471619, -0.28551934],
       [ 1.3583682 ,  2.32165112],
       [ 0.20666648, -0.40269554],
       [-1.13698554,  0.38824381],
       [ 1.16641791, -1.0178706 ],
       [-1.32893582, -0.46128364],
       [ 1.55031849,  1.09130101],
       [-1.04101039, -1.16434085],
       [-0.65710982, -1.0764587 ],
       [-0.08125895,  0.12459736],
       [-0.1772341 , -1.10575275],
       [-0.27320924,  0.03671521],
       [-1.80881154, -1.51586945],
       [-0.27320924, -1.39869325],
       [ 1.3583682 ,  1.26706532],
       [-0.1772341 ,  1.38424152],
       [-0.56113467,  0.44683191],
       [-0.75308496, -0.25622529],
       [-0.94503525, -0.34410744],
       [ 1.26239306,  1.85294632],
       [ 0.30264162,  0.03671521],
       [ 1.07044277,  0.53471406],
       [-0.08125895, -0.51987174],
       [ 0.68654219, -1.4279873 ],
       [ 2.03019421,  1.73577012],
       [ 0.78251734, -1.4279873 ],
       [ 0.39861676,  1.09130101],
       [-0.27320924,  0.24177356],
       [ 1.64629363,  1.73577012],
       [-0.46515953, -1.16434085],
       [-1.23296068,  0.47612596],
       [-1.7128364 ,  0.32965571]])

## 6. Model Training

In [44]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)
model.fit(X_train,y_train)

LogisticRegression(random_state=0)

### Predicting whether new customer with Age & Salary will buy or not

In [51]:
age = int(input("Enter New Customer Age: "))
sal = int(input("Enter New Customer Salary: "))
newCust = [[age,sal]]
res = model.predict(sc.transform(newCust))
print(res)
if res == 1:
    print("customer will buy!")
else:
    print("customer won't buy!")

Enter New Customer Age:  56
Enter New Customer Salary:  100000

[1]
customer will buy!

## Prediction for all Test data

In [45]:
y_pred = model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]]

### Accuracy score

In [46]:
from sklearn.metrics import accuracy_score
print("Accuracy of the Model: {0}%".format(accuracy_score(y_test,y_pred)*100))

Accuracy of the Model: 80.0%

# THE END!